name: Check Devbox
run-name: Check Devbox - ${{ github.run_id }} - @${{ github.actor }}

on:
  pull_request:

  merge_group:

jobs:
  changes:
     name: Check for relevant changes
     runs-on: ubuntu-latest
     permissions:
       pull-requests: read
     outputs:
       changed: ${{ steps.changes.outputs.changed }}
     steps:
       - name: Checkout
         if: ${{ github.event_name == 'merge_group' }}
         uses: actions/checkout@v4
       - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
         id: changes
         with:
           base: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
           ref: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
           filters: |
             changed:
               - .github/workflows/check-devbox.yaml
               - 'devbox.json'
               - 'devbox.lock'
               - 'build.assets/flake/**'

  check-devbox:
    name: Check Devbox
    needs: changes
    if: ${{ !startsWith(github.head_ref, 'dependabot/') && needs.changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@a0bd99f5de03156cc900bbbeb830f07d3d39aab0 # v0.6.1
        with:
          enable-cache: true
          devbox-version: 0.5.10
          sha256-sum: a4f66cacf6091530f3d51148df83a08353906496c8ada001b0edd7ac29226dc5
